# Generated by Django 5.1.8 on 2025-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='dictionaries',
            field=models.ManyToManyField(error_messages={'required': 'Du måste välja minst en ordlista för begreppet. Annars kan du inte spara.'}, related_name='concept', to='term_list.dictionary'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalconcept',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
