# Generated by Django 2.2.5 on 2020-02-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponeraBegreppDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begrepp_kontext', models.TextField()),
                ('datum', models.DateTimeField()),
                ('epost', models.EmailField(max_length=254)),
                ('namn', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ny', 'Ny')], default='Ny', max_length=50)),
                ('telefon', models.CharField(max_length=13)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='term_list.Begrepp')),
            ],
            options={
                'verbose_name_plural': 'Ifrågasatt Begrepp Definitioner',
            },
        ),
    ]
