# Generated by Django 5.1.8 on 2025-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0002_alter_concept_definition_alter_concept_dictionaries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AlterModelOptions(
            name='conceptcomment',
            options={'verbose_name_plural': 'Concept comments'},
        ),
        migrations.AlterModelOptions(
            name='conceptexternalfiles',
            options={'verbose_name': 'Uploaded File', 'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AlterModelOptions(
            name='configurationoptions',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterModelOptions(
            name='groupattribute',
            options={'verbose_name': 'Attribute Group', 'verbose_name_plural': 'Attribute Groups'},
        ),
        migrations.AlterModelOptions(
            name='grouphierarchy',
            options={'verbose_name': 'Group Hierarchy', 'verbose_name_plural': 'Group Hierarchy'},
        ),
        migrations.AlterModelOptions(
            name='historicalattributevalue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Attribute Value'},
        ),
        migrations.AlterModelOptions(
            name='historicalconcept',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Concept'},
        ),
        migrations.AlterModelOptions(
            name='metadatasearchtrack',
            options={'verbose_name': 'Search Metadata', 'verbose_name_plural': 'Search Metadata'},
        ),
        migrations.AlterModelOptions(
            name='searchtrack',
            options={'verbose_name_plural': 'Search data'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.AlterModelOptions(
            name='taskorderer',
            options={'verbose_name': 'Requester', 'verbose_name_plural': 'Requesters'},
        ),
        migrations.AlterField(
            model_name='concept',
            name='dictionaries',
            field=models.ManyToManyField(related_name='concept', to='term_list.dictionary'),
        ),
    ]
