# Generated by Django 5.1.8 on 2025-10-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0003_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskorderer',
            name='concept',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concept', to='term_list.concept'),
            preserve_default=False,
        ),
    ]
