# Generated by Django 5.1.8 on 2025-10-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0004_taskorderer_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskorderer',
            name='concept',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_requester', to='term_list.concept'),
        ),
    ]
