# Generated by Django 5.2.11 on 2026-02-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("term_list", "0005_alter_taskorderer_concept"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"verbose_name": "Attribut", "verbose_name_plural": "Attribut"},
        ),
        migrations.AlterModelOptions(
            name="attributevalue",
            options={
                "verbose_name": "Attribut Värde",
                "verbose_name_plural": "Attribute Värden",
            },
        ),
        migrations.AlterModelOptions(
            name="concept",
            options={"verbose_name": "Begrepp", "verbose_name_plural": "Begrepp"},
        ),
        migrations.AlterModelOptions(
            name="conceptcomment",
            options={
                "verbose_name": "Begrepp kommentar",
                "verbose_name_plural": "Begrepp kommentarer",
            },
        ),
        migrations.AlterModelOptions(
            name="conceptexternalfiles",
            options={
                "verbose_name": "Uppladdad fil",
                "verbose_name_plural": "Uppladdade filer",
            },
        ),
        migrations.AlterModelOptions(
            name="configurationoptions",
            options={
                "verbose_name": "inställning",
                "verbose_name_plural": "Inställningar",
            },
        ),
        migrations.AlterModelOptions(
            name="dictionary",
            options={"verbose_name": "Orbok", "verbose_name_plural": "Ordböcker"},
        ),
        migrations.AlterModelOptions(
            name="groupattribute",
            options={
                "ordering": ["position", "attribute__name"],
                "verbose_name": "Attribut Grupp",
                "verbose_name_plural": "Attribut Grupper",
            },
        ),
        migrations.AlterModelOptions(
            name="grouphierarchy",
            options={
                "verbose_name": "Grupp Hierarki",
                "verbose_name_plural": "Group Hierarki",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalattributevalue",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Attribut Värde",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalconcept",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Begrepp",
            },
        ),
        migrations.AlterModelOptions(
            name="metadatasearchtrack",
            options={
                "verbose_name": "Sök Metadata",
                "verbose_name_plural": "Sök Metadata",
            },
        ),
        migrations.AlterModelOptions(
            name="searchtrack",
            options={"verbose_name_plural": "Sök data"},
        ),
        migrations.AlterModelOptions(
            name="taskorderer",
            options={
                "verbose_name": "Beställare",
                "verbose_name_plural": "Beställaren",
            },
        ),
        # migrations.AddField(
        #     model_name="groupattribute",
        #     name="visible",
        #     field=models.BooleanField(default=True),
        # ),
        migrations.AddConstraint(
            model_name="groupattribute",
            constraint=models.UniqueConstraint(
                fields=("group", "position"),
                name="unique_position_per_group",
            ),
        ),
    ]
