# Generated by Django 3.0.3 on 2020-03-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0008_auto_20200303_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SökData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sök_term', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('sök_timestamp', models.DateTimeField(auto_now_add=True)),
                ('records_returned', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sök data',
            },
        ),
    ]
