# Generated by Django 3.0.3 on 2020-03-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0009_sökdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sökdata',
            old_name='ip_address',
            new_name='ip_adress',
        ),
    ]
