# Generated by Django 3.0.3 on 2020-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0010_auto_20200305_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='SökFörklaring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sök_term', models.CharField(max_length=255)),
                ('ip_adress', models.GenericIPAddressField()),
                ('sök_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
