# Generated by Django 3.0.3 on 2020-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0011_sökförklaring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opponerabegreppdefinition',
            options={'verbose_name_plural': 'Kommenterade Begrepp'},
        ),
    ]
