# Generated by Django 3.0.3 on 2020-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0016_auto_20200312_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='externt_register',
            new_name='källa',
        ),
    ]
