# Generated by Django 3.0.3 on 2020-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0017_auto_20200320_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='externt_register',
            field=models.CharField(default='Inte definierad', max_length=255, null=True),
        ),
    ]
