# Generated by Django 3.0.3 on 2020-03-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0019_auto_20200323_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaÄrende',
        ),
        migrations.AlterModelOptions(
            name='opponerabegreppdefinition',
            options={'verbose_name_plural': 'Kommenterade Begrepp'},
        ),
        migrations.RenameField(
            model_name='begrepp',
            old_name='vgr_id',
            new_name='id_vgr',
        ),
    ]
