# Generated by Django 3.0.3 on 2020-04-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0022_delete_begreppbeställdeavanvändare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='externt_register',
            new_name='annan_ordlista',
        ),
    ]
