# Generated by Django 3.0.3 on 2020-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0024_auto_20200609_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='begrepp_version_nummer',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='beställare_datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
