# Generated by Django 3.0.3 on 2020-09-23 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0030_begrepp_term_i_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='datum_skapat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum skapat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='term_i_system',
            field=models.CharField(blank=True, choices=[('Millennium', 'Millennium'), ('Annat system', 'Annat system'), ('VGR Begreppsystem', 'VGR Begreppsystem')], max_length=255, null=True, verbose_name='Används i system'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='utländsk_term',
            field=models.CharField(max_length=255),
        ),
    ]
