# Generated by Django 3.0.3 on 2020-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0034_auto_20201008_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='begrepp_version_nummer',
            field=models.DateTimeField(auto_now=True, verbose_name='Senaste ändring'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('För validering', 'För validering'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('För validering', 'För validering'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
    ]
