# Generated by Django 3.0.3 on 2020-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0035_auto_20201023_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='alternativ_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
