# Generated by Django 2.2.5 on 2020-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0036_auto_20201023_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='email_extra',
            field=models.TextField(null=True),
        ),
    ]
