# Generated by Django 2.2.5 on 2020-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0037_begrepp_email_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='email_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
