# Generated by Django 3.0.3 on 2021-10-05 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0041_auto_20210429_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='alternativ_definition',
            new_name='tidigare_definition_och_källa',
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='utländsk_definition',
        ),
        migrations.AddField(
            model_name='begreppexternalfiles',
            name='kommentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term_list.OpponeraBegreppDefinition'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Önskad Översättning', 'Önskad Översättning'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Önskad Översättning', 'Önskad Översättning'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Tillåten', 'Tillåten'), ('Inte angiven', 'Inte angiven')], default='Inte angiven', max_length=255),
        ),
    ]
