# Generated by Django 3.0.3 on 2022-04-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0043_historicalbegrepp_historicalsynonym'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpponeraBegreppDefinition',
            new_name='KommenteraBegreppDefinition',
        ),
    ]
