# Generated by Django 3.2.13 on 2022-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0046_auto_20220823_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='link',
            field=models.URLField(blank=True, help_text='Länk till begreppsutredning', null=True, verbose_name='länk'),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='link',
            field=models.URLField(blank=True, help_text='Länk till begreppsutredning', null=True, verbose_name='länk'),
        ),
    ]
