# Generated by Django 4.2.15 on 2024-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('term_list', '0049_remove_begrepp_email_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doman',
            name='users',
        ),
        migrations.AddField(
            model_name='doman',
            name='groups',
            field=models.ManyToManyField(related_name='domains', to='auth.group'),
        ),
    ]
