# Generated by Django 4.2.15 on 2024-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0051_alter_begrepp_beställare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doman',
            name='groups',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domains', models.ManyToManyField(blank=True, related_name='groups', to='term_list.doman')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
