# Generated by Django 4.2.15 on 2024-08-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('term_list', '0052_remove_doman_groups_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.ManyToManyField(blank=True, related_name='extended_groups', to='term_list.doman')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Extended Groups',
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
