# Generated by Django 4.2.15 on 2024-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('term_list', '0056_begrepp_dictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='dictionaries', to='auth.group'),
        ),
    ]
