# Generated by Django 4.2.15 on 2024-09-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0059_dictionary_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='beställare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begrepp', to='term_list.bestallare'),
        ),
    ]
