# Generated by Django 5.1.1 on 2024-09-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0060_alter_begrepp_beställare'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visible', models.BooleanField()),
                ('config', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inställningar',
            },
        ),
    ]
