# Generated by Django 5.1.3 on 2024-11-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0066_rename_word_attributevalue_term_concept_changed_at_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='attributevalue',
        #     old_name='word',
        #     new_name='term',
        # ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_text',
            field=models.TextField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='changed_at',
        #     field=models.DateTimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='dictionaries',
        #     field=models.ManyToManyField(related_name='concept', to='term_list.dictionary'),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='status',
        #     field=models.CharField(choices=[('Avråds', 'Avråds'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår')], max_length=10, null=True),
        # ),
    ]
