# Generated by Django 5.1.3 on 2024-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0067_rename_word_attributevalue_term_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='word',
            new_name='term',
        ),
        migrations.AddField(
            model_name='concept',
            name='changed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='dictionaries',
            field=models.ManyToManyField(related_name='concept', to='term_list.dictionary'),
        ),
        migrations.AddField(
            model_name='concept',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår')], max_length=10, null=True),
        ),
    ]
