# Generated by Django 5.1.3 on 2024-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0069_attributevalue_value_url_alter_attribute_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår')], max_length=15, null=True),
        ),
    ]
