# Generated by Django 5.1.3 on 2024-11-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0070_alter_concept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='term',
            field=models.CharField(max_length=255),
        ),
    ]
