# Generated by Django 5.1.3 on 2024-11-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0071_alter_concept_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsynonym',
            name='concept',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='term_list.concept'),
        ),
        migrations.AddField(
            model_name='synonym',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term_list.concept'),
        ),
    ]
