# Generated by Django 5.1.3 on 2024-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0073_attribute_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
