# Generated by Django 5.1.3 on 2024-12-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0076_rename_sökförklaring_metadatasearchtrack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskorderer',
            old_name='beställare_datum',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='taskorderer',
            old_name='beställare_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='taskorderer',
            old_name='önskad_slutdatum',
            new_name='finished_by_date',
        ),
        migrations.RenameField(
            model_name='taskorderer',
            old_name='beställare_namn',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taskorderer',
            old_name='beställare_telefon',
            new_name='telephone',
        ),
    ]
