# Generated by Django 5.1.3 on 2024-12-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term_list', '0077_remove_historicalsynonym_begrepp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalconcept',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': ['changed_at', 'definition']},
        ),
    ]
