# Generated by Django 5.1.3 on 2024-12-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('term_list', '0079_remove_begreppexternalfiles_begrepp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='auth.group'),
        ),
    ]
