version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: unless-stopped
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      PMA_ARBITRARY: 1
    networks:
      - local

networks:
  local:
    name: local
    external: true
