# Generated by Django 2.2.5 on 2020-01-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestallare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beställare_datum', models.DateField()),
                ('beställare_email', models.EmailField(max_length=254)),
                ('beställare_kontext', models.CharField(max_length=255)),
                ('beställare_namn', models.CharField(max_length=255)),
                ('beställare_telefon', models.IntegerField()),
                ('domain_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domän_namn', models.CharField(max_length=255)),
                ('domän_email', models.CharField(max_length=255)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.Bestallare')),
            ],
        ),
        migrations.CreateModel(
            name='Begrepp',
            fields=[
                ('begrepp_key', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.TextField()),
                ('kontext_beskrivning', models.TextField()),
                ('synonym', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('utländsk_definition', models.TextField()),
                ('utländsk_term', models.CharField(max_length=255)),
                ('begrepp_version_nummer', models.IntegerField()),
                ('beställare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.Bestallare')),
            ],
        ),
    ]
