# Generated by Django 4.2.1 on 2023-05-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Begrepp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begrepp_kontext', models.TextField(default='Inte definierad')),
                ('senaste_ändring', models.DateTimeField(auto_now=True, verbose_name='Senaste ändring')),
                ('datum_skapat', models.DateTimeField(auto_now_add=True, verbose_name='Datum skapat')),
                ('definition', models.TextField(blank=True)),
                ('tidigare_definition_och_källa', models.TextField(blank=True, null=True)),
                ('externt_id', models.CharField(max_length=255, null=True, verbose_name='Kod')),
                ('källa', models.CharField(max_length=255, null=True)),
                ('annan_ordlista', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255)),
                ('term', models.CharField(default='Angavs ej', max_length=255)),
                ('plural', models.CharField(max_length=10, null=True)),
                ('utländsk_term', models.CharField(blank=True, max_length=255)),
                ('id_vgr', models.CharField(max_length=255, null=True)),
                ('anmärkningar', models.TextField(null=True)),
                ('kommentar_handläggning', models.TextField(null=True)),
                ('term_i_system', models.CharField(blank=True, choices=[('Millennium', 'Millennium'), ('Annat system', 'Annat system'), ('VGR Begreppsystem', 'VGR Begreppsystem')], max_length=255, null=True, verbose_name='Används i system')),
                ('link', models.URLField(blank=True, help_text='Länk till externt dokument', null=True, verbose_name='Länk till begreppsutredning')),
                ('usage_recommendation', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Begrepp',
            },
        ),
        migrations.CreateModel(
            name='Bestallare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beställare_namn', models.CharField(blank=True, max_length=255)),
                ('beställare_datum', models.DateTimeField(auto_now_add=True)),
                ('önskad_slutdatum', models.DateTimeField(blank=True, null=True)),
                ('beställare_email', models.EmailField(max_length=254)),
                ('beställare_telefon', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Beställare',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main', max_length=72)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ordlistor',
            },
        ),
        migrations.CreateModel(
            name='SökData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sök_term', models.CharField(max_length=255)),
                ('ip_adress', models.GenericIPAddressField()),
                ('sök_timestamp', models.DateTimeField(auto_now_add=True)),
                ('records_returned', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sök data',
            },
        ),
        migrations.CreateModel(
            name='SökFörklaring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sök_term', models.CharField(max_length=255)),
                ('ip_adress', models.GenericIPAddressField()),
                ('sök_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sök Förklaring',
            },
        ),
        migrations.CreateModel(
            name='TypeOfRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerofDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main', max_length=72)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Region',
            },
        ),
        migrations.CreateModel(
            name='KommenteraBegrepp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begrepp_kontext', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('epost', models.EmailField(max_length=254)),
                ('namn', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50)),
                ('telefon', models.CharField(max_length=30)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Kommenterade Begrepp',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBegrepp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('begrepp_kontext', models.TextField(default='Inte definierad')),
                ('senaste_ändring', models.DateTimeField(blank=True, editable=False, verbose_name='Senaste ändring')),
                ('datum_skapat', models.DateTimeField(blank=True, editable=False, verbose_name='Datum skapat')),
                ('definition', models.TextField(blank=True)),
                ('tidigare_definition_och_källa', models.TextField(blank=True, null=True)),
                ('externt_id', models.CharField(max_length=255, null=True, verbose_name='Kod')),
                ('källa', models.CharField(max_length=255, null=True)),
                ('annan_ordlista', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255)),
                ('term', models.CharField(default='Angavs ej', max_length=255)),
                ('plural', models.CharField(max_length=10, null=True)),
                ('utländsk_term', models.CharField(blank=True, max_length=255)),
                ('id_vgr', models.CharField(max_length=255, null=True)),
                ('anmärkningar', models.TextField(null=True)),
                ('kommentar_handläggning', models.TextField(null=True)),
                ('term_i_system', models.CharField(blank=True, choices=[('Millennium', 'Millennium'), ('Annat system', 'Annat system'), ('VGR Begreppsystem', 'VGR Begreppsystem')], max_length=255, null=True, verbose_name='Används i system')),
                ('link', models.URLField(blank=True, help_text='Länk till externt dokument', null=True, verbose_name='Länk till begreppsutredning')),
                ('usage_recommendation', models.CharField(max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beställare', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordbok.bestallare')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'datum_skapat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Doman',
            fields=[
                ('domän_id', models.AutoField(primary_key=True, serialize=False)),
                ('domän_kontext', models.TextField(blank=True, null=True)),
                ('domän_namn', models.CharField(max_length=255)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begrepp_fk', to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Domäner',
            },
        ),
        migrations.CreateModel(
            name='BegreppExternalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_file', models.FileField(blank=True, null=True, upload_to='')),
                ('begrepp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.begrepp')),
                ('kommentar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordbok.kommenterabegrepp')),
            ],
            options={
                'verbose_name_plural': 'Uppladdade filer',
            },
        ),
        migrations.AddField(
            model_name='begrepp',
            name='beställare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.bestallare'),
        ),
        migrations.AddField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ManyToManyField(to='ordbok.dictionary'),
        ),
        migrations.CreateModel(
            name='TermRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_term', to='ordbok.begrepp')),
                ('child_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_term', to='ordbok.begrepp')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.typeofrelationship')),
            ],
            options={
                'indexes': [models.Index(fields=['base_term', 'child_term'], name='ordbok_term_base_te_47d2b9_idx'), models.Index(fields=['base_term'], name='base_term_idx')],
            },
        ),
    ]
