# Generated by Django 2.2.5 on 2020-02-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Begrepp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begrepp_kontext', models.TextField()),
                ('begrepp_version_nummer', models.DateTimeField()),
                ('definition', models.TextField()),
                ('externt_id', models.CharField(max_length=255, null=True)),
                ('externt_register', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ny', 'Ny')], default='Ny', max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('utländsk_definition', models.TextField(default='Inte definierad')),
                ('utländsk_term', models.CharField(default='Inte definierad', max_length=255)),
                ('vgr_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Begrepp',
            },
        ),
        migrations.CreateModel(
            name='Bestallare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beställare_namn', models.CharField(max_length=255)),
                ('beställare_datum', models.DateTimeField()),
                ('beställare_email', models.EmailField(max_length=254)),
                ('beställare_telefon', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Beställare',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordbok.Begrepp')),
            ],
            options={
                'verbose_name_plural': 'Synonymer',
            },
        ),
        migrations.CreateModel(
            name='Doman',
            fields=[
                ('domän_id', models.IntegerField(primary_key=True, serialize=False)),
                ('domän_kontext', models.TextField()),
                ('domän_namn', models.CharField(max_length=255)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordbok.Begrepp')),
            ],
            options={
                'verbose_name_plural': 'Domäner',
            },
        ),
        migrations.AddField(
            model_name='begrepp',
            name='beställare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.Bestallare'),
        ),
    ]
