# Generated by Django 2.2.5 on 2020-02-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='begrepp',
            options={'verbose_name_plural': 'Begrepp'},
        ),
        migrations.AlterModelOptions(
            name='bestallare',
            options={'verbose_name_plural': 'Beställare'},
        ),
        migrations.AlterModelOptions(
            name='doman',
            options={'verbose_name_plural': 'Domäner'},
        ),
        migrations.RenameField(
            model_name='begrepp',
            old_name='kontext_beskrivning',
            new_name='begrepp_kontext',
        ),
        migrations.RenameField(
            model_name='begrepp',
            old_name='begrepp',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='begrepp_key',
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='synonym',
        ),
        migrations.RemoveField(
            model_name='bestallare',
            name='beställare_kontext',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='externt_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='begrepp',
            name='externt_register',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='begrepp',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ny', 'Ny')], default='Ny', max_length=255),
        ),
        migrations.AddField(
            model_name='begrepp',
            name='vgr_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='begrepp_version_nummer',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('synonym_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordbok.Begrepp')),
            ],
            options={
                'verbose_name_plural': 'Synonymer',
            },
        ),
    ]
