# Generated by Django 2.2.5 on 2020-02-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='beställare_id',
            new_name='beställare',
        ),
    ]
