# Generated by Django 2.2.5 on 2020-02-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0002_auto_20200207_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synonym',
            old_name='synonym_id',
            new_name='begrepp',
        ),
    ]
