# Generated by Django 4.2.1 on 2023-06-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0002_alter_begrepp_anmärkningar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='externt_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='begrepp',
            old_name='id_vgr',
            new_name='official_id',
        ),
        migrations.RenameField(
            model_name='historicalbegrepp',
            old_name='externt_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='historicalbegrepp',
            old_name='id_vgr',
            new_name='official_id',
        ),
    ]
