# Generated by Django 2.2.5 on 2020-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0003_auto_20200221_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ny', 'Ny')], default='Klar', max_length=255),
        ),
    ]
