# Generated by Django 4.2.1 on 2023-08-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0003_rename_externt_id_begrepp_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerofdictionary',
            name='concept',
        ),
        migrations.AddField(
            model_name='historicalbegrepp',
            name='dictionaries',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordbok.dictionary'),
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='dictionaries',
        ),
        migrations.DeleteModel(
            name='Doman',
        ),
        migrations.DeleteModel(
            name='OwnerofDictionary',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordbok.dictionary'),
            preserve_default=False,
        ),
    ]
