# Generated by Django 4.2.1 on 2023-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0004_remove_ownerofdictionary_concept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbegrepp',
            name='dictionaries',
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='dictionaries',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ManyToManyField(to='ordbok.dictionary'),
        ),
    ]
