# Generated by Django 2.2.5 on 2020-02-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0004_synonym_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synonym',
            old_name='status',
            new_name='synonym_status',
        ),
    ]
