# Generated by Django 4.2.1 on 2023-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0005_remove_historicalbegrepp_dictionaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofrelationship',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ManyToManyField(related_name='dictionary_set', to='ordbok.dictionary'),
        ),
    ]
