# Generated by Django 2.2.5 on 2020-03-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0005_auto_20200221_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='anmärkningar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='begrepp',
            name='kommentar_handläggning',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Klar', 'Klar'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
    ]
