# Generated by Django 3.0.3 on 2020-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0006_auto_20200302_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='anmärkningar',
            field=models.TextField(default='Inte definierad', null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='begrepp_kontext',
            field=models.TextField(default='Inte definierad'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='externt_id',
            field=models.CharField(default='Inte definierad', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='externt_register',
            field=models.CharField(default='Inte definierad', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='kommentar_handläggning',
            field=models.TextField(default='Inte definierad', null=True),
        ),
    ]
