# Generated by Django 3.0.3 on 2020-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0007_auto_20200303_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='vgr_id',
            field=models.CharField(default='Inte definierad', max_length=255, null=True),
        ),
    ]
