# Generated by Django 3.0.3 on 2020-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0014_auto_20200312_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='synonym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Tillåten', 'Tillåten'), ('Rekommenderad', 'Rekommenderad'), ('Inte angiven', 'Inte angiven')], default='Inte angiven', max_length=255),
        ),
    ]
