# Generated by Django 3.0.3 on 2020-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0021_auto_20200408_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BegreppBeställdeAvAnvändare',
        ),
    ]
