# Generated by Django 3.0.3 on 2020-08-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0025_auto_20200713_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sökförklaring',
            options={'verbose_name': 'Sök Förklaring'},
        ),
    ]
