# Generated by Django 3.0.3 on 2020-08-28 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0026_auto_20200826_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestallare',
            name='önskad_slutdatum',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
