# Generated by Django 3.0.3 on 2020-08-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0026_auto_20200828_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='support_files',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
