# Generated by Django 3.0.3 on 2020-09-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0028_auto_20200901_1300'),
        ('ordbok', '0026_auto_20200826_1105'),
    ]

    operations = [
    ]
