# Generated by Django 2.2.5 on 2020-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0030_begrepp_term_i_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='term',
            field=models.CharField(default='Angavs ej', max_length=255),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='term_i_system',
            field=models.CharField(blank=True, choices=[('Millennium', 'Millennium'), ('Annat system', 'Annat system'), ('VGR Begreppsystem', 'VGR Begreppsystem')], max_length=255, null=True, verbose_name='Används i system'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='utländsk_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='beställare_namn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='beställare_telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='önskad_slutdatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
    ]
