# Generated by Django 3.0.3 on 2020-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0031_auto_20200923_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='term',
            field=models.CharField(default='Angavs ej', max_length=255),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='utländsk_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='begreppexternalfiles',
            name='support_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='beställare_namn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='beställare_telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bestallare',
            name='önskad_slutdatum',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('Inte definierad', 'Inte definierad'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
    ]
