# Generated by Django 3.0.3 on 2020-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0034_auto_20201008_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='opponerabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår'), ('Publicera ej', 'Publicera ej'), ('Preliminär', 'Preliminär'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
    ]
