# Generated by Django 3.0.3 on 2021-09-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0041_auto_20210429_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='begreppexternalfiles',
            name='kommentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordbok.OpponeraBegreppDefinition'),
        ),
    ]
