# Generated by Django 3.0.3 on 2021-10-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordbok', '0042_auto_20211005_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSynonym',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('synonym', models.CharField(blank=True, max_length=255, null=True)),
                ('synonym_status', models.CharField(choices=[('Avråds', 'Avråds'), ('Tillåten', 'Tillåten'), ('Inte angiven', 'Inte angiven')], default='Inte angiven', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('begrepp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordbok.Begrepp')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical synonym',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBegrepp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('begrepp_kontext', models.TextField(default='Inte definierad')),
                ('begrepp_version_nummer', models.DateTimeField(blank=True, editable=False, verbose_name='Senaste ändring')),
                ('datum_skapat', models.DateTimeField(blank=True, editable=False, verbose_name='Datum skapat')),
                ('definition', models.TextField(blank=True)),
                ('tidigare_definition_och_källa', models.TextField(blank=True, null=True)),
                ('externt_id', models.CharField(default='Inte definierad', max_length=255, null=True, verbose_name='Kod')),
                ('källa', models.CharField(default='Inte definierad', max_length=255, null=True)),
                ('annan_ordlista', models.CharField(default='Inte definierad', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Önskad Översättning', 'Önskad Översättning'), ('Översättning', 'Översättning'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255)),
                ('term', models.CharField(default='Angavs ej', max_length=255)),
                ('utländsk_term', models.CharField(blank=True, max_length=255)),
                ('id_vgr', models.CharField(default='Inte definierad', max_length=255, null=True)),
                ('anmärkningar', models.TextField(default='Inte definierad', null=True)),
                ('kommentar_handläggning', models.TextField(default='Inte definierad', null=True)),
                ('term_i_system', models.CharField(blank=True, choices=[('Millennium', 'Millennium'), ('Annat system', 'Annat system'), ('VGR Begreppsystem', 'VGR Begreppsystem')], max_length=255, null=True, verbose_name='Används i system')),
                ('email_extra', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beställare', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ordbok.Bestallare')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'datum_skapat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
