# Generated by Django 3.2.13 on 2022-05-05 13:03

from django.db import migrations, models
import django.db.models.deletion
# from ordbok.models import KommenteraBegreppDefinition, KommenteraBegrepp

def move_data(apps, schema_editor):

    old_comments = KommenteraBegreppDefinition.objects.all()
    KommenteraBegrepp.objects.bulk_create(old_comments)


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0044_auto_20220412_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='begrepp',
            old_name='begrepp_version_nummer',
            new_name='senaste_ändring',
        ),
        migrations.RenameField(
            model_name='historicalbegrepp',
            old_name='begrepp_version_nummer',
            new_name='senaste_ändring',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='plural',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalbegrepp',
            name='plural',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='anmärkningar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='annan_ordlista',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='externt_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='id_vgr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='kommentar_handläggning',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='källa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='anmärkningar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='annan_ordlista',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='externt_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='id_vgr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='kommentar_handläggning',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='källa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=255),
        ),
        migrations.AlterField(
            model_name='kommenterabegreppdefinition',
            name='status',
            field=models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50),
        ),
        migrations.CreateModel(
            name='KommenteraBegrepp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begrepp_kontext', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('epost', models.EmailField(max_length=254)),
                ('namn', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Avråds', 'Avråds'), ('Avställd', 'Avställd'), ('Beslutad', 'Beslutad'), ('Definiera ej', 'Definiera ej'), ('För validering', 'För validering'), ('Internremiss', 'Internremiss'), ('Preliminär', 'Preliminär'), ('Publicera ej', 'Publicera ej'), ('Pågår', 'Pågår'), ('Ej Påbörjad', 'Ej Påbörjad')], default='Ej Påbörjad', max_length=50)),
                ('telefon', models.CharField(max_length=30)),
                ('begrepp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Kommenterade Begrepp',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('begrepp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Ordlista',
            },
        ),
        migrations.AlterField(
            model_name='begreppexternalfiles',
            name='kommentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordbok.kommenterabegrepp'),
        ),

        migrations.RunPython(move_data, hints={'target_db': 'default'}),

        migrations.DeleteModel(
            name='KommenteraBegreppDefinition'
        ),
    ]



