# Generated by Django 3.2.13 on 2022-05-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0045_auto_20220505_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='begreppexternalfiles',
            options={'verbose_name_plural': 'Uppladdade filer'},
        ),
        migrations.RemoveField(
            model_name='begrepp',
            name='email_extra',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='begrepp',
        ),
        migrations.RemoveField(
            model_name='historicalbegrepp',
            name='email_extra',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ManyToManyField(to='ordbok.Dictionary'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='title',
            field=models.CharField(default='Main', max_length=72),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ConnectedTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_term', to='ordbok.begrepp')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.typeofrelationship')),
                ('to_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_term', to='ordbok.begrepp')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('begrepp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordbok.begrepp')),
            ],
            options={
                'verbose_name_plural': 'Ordlista',
            },
        ),
    ]
