# Generated by Django 3.2.13 on 2022-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0046_auto_20220512_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectedTerms',
            new_name='TermRelationship',
        ),
        migrations.AddField(
            model_name='begrepp',
            name='usage_recommendation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalbegrepp',
            name='usage_recommendation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
