# Generated by Django 3.2.13 on 2022-08-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0047_auto_20220824_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='begrepp',
            name='link',
            field=models.URLField(blank=True, help_text='Länk till externt dokument', null=True, verbose_name='Länk till begreppsutredning'),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='link',
            field=models.URLField(blank=True, help_text='Länk till externt dokument', null=True, verbose_name='Länk till begreppsutredning'),
        ),
    ]
