# Generated by Django 3.2.13 on 2022-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0047_auto_20220513_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Template Text',
            },
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='begrepp',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='title',
            field=models.CharField(default='Main', max_length=72),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
