# Generated by Django 3.2.13 on 2022-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0048_auto_20220607_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='begrepp',
        ),
        migrations.AlterField(
            model_name='templatetext',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSynonym',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
