# Generated by Django 4.2.15 on 2024-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0054_dictionary_remove_extendedgroup_domains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='begrepp',
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='anmärkningar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='annan_ordlista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='externt_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='id_vgr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='kommentar_handläggning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='begrepp',
            name='källa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='anmärkningar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='annan_ordlista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='externt_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='id_vgr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='kommentar_handläggning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbegrepp',
            name='källa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
