# Generated by Django 4.2.15 on 2024-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0055_remove_dictionary_begrepp_alter_begrepp_anmärkningar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='begrepp',
            name='dictionaries',
            field=models.ManyToManyField(related_name='begrepp', to='ordbok.dictionary'),
        ),
    ]
