# Generated by Django 4.2.15 on 2024-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0057_dictionary_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='dictionary_long_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_name',
            field=models.CharField(max_length=50),
        ),
    ]
