# Generated by Django 4.2.15 on 2024-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0058_dictionary_dictionary_long_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
