# Generated by Django 5.1.3 on 2024-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0062_attribute_businessunit_concept_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='concept',
        #     name='changed_at',
        #     field=models.DateTimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='created_at',
        #     field=models.DateTimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='dictionaries',
        #     field=models.ManyToManyField(related_name='concept', to='ordbok.dictionary'),
        # ),
    ]
