# Generated by Django 5.1.3 on 2024-11-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0064_concept_changed_at_concept_created_at_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='concept',
        #     name='changed_at',
        #     field=models.DateTimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='dictionaries',
        #     field=models.ManyToManyField(related_name='concept', to='ordbok.dictionary'),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='status',
        #     field=models.CharField(choices=[('Avråds', 'Avråds'), ('Beslutad', 'Beslutad'), ('Pågår', 'Pågår')], max_length=10, null=True),
        # ),
    ]
