# Generated by Django 5.1.3 on 2024-11-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0065_concept_changed_at_concept_dictionaries_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='attributevalue',
        #     old_name='word',
        #     new_name='term',
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='changed_at',
        #     field=models.DateTimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='concept',
        #     name='dictionaries',
        #     field=models.ManyToManyField(related_name='concept', to='ordbok.dictionary'),
        # ),
    ]
