# Generated by Django 5.1.3 on 2024-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0068_rename_word_attributevalue_term_concept_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='value_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('text', 'Text'), ('url', 'URL')], max_length=50),
        ),
    ]
