# Generated by Django 5.1.3 on 2024-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0072_historicalsynonym_concept_synonym_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='display_name',
            field=models.CharField(default='display_name', max_length=255),
            preserve_default=False,
        ),
    ]
