# Generated by Django 5.1.3 on 2024-12-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0074_attribute_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='field_positions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Senaste ändring'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum skapat'),
        ),
    ]
