# Generated by Django 5.1.3 on 2024-12-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ordbok', '0078_change_historical_concept'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='attribute',
        #     name='group',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='auth.group'),
        #     preserve_default=False,
        # ),
        # migrations.CreateModel(
        #     name='GroupHierarchy',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_groups', to='auth.group')),
        #         ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='auth.group')),
        #     ],
        # ),
        migrations.DeleteModel(
            name='BusinessUnitAttribute',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),

    ]
