# Generated by Django 5.1.3 on 2024-12-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ordbok', '0080_remove_kommenterabegrepp_begrepp_and_more'),
    ]

    operations = [
  
        migrations.CreateModel(
            name='GroupHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_groups', to='auth.group')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='auth.group')),
            ],
        ),

    ]
