# Generated by Django 5.1.3 on 2024-12-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ordbok', '0081_remove_synonym_begrepp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordbok.attribute')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('group', 'attribute')},
            },
        ),
    ]
