# Generated by Django 5.1.3 on 2024-12-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordbok', '0082_remove_begreppexternalfiles_begrepp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='position',
        ),
    ]
